version: '3.8'
services:

  node-nuxt:
    container_name: classis-node-nuxt
    build:
      context: ./
      dockerfile: node-nuxt.Dockerfile
    tty: true
    ports:
      - "3004:3000"
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    networks:
      - classis-network

  node-nest:
    container_name: classis-node-nest
    build:
      context: ./
      dockerfile: node-nest.Dockerfile
    tty: true
    ports:
      - "3005:3000"
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    networks:
      - classis-network

  nginx-apigateway:
    container_name: classis-nginx-apigateway
    build:
      context: ./
      dockerfile: nginx-apigateway.Dockerfile
    tty: true
    ports:
      - "8000:80"
      - "4043:443"
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - ./nginx-apigateway-default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - classis-network
    depends_on:
      - php-apigateway

  php-apigateway:
    container_name: classis-php-apigateway
    build:
      context: ./
      dockerfile: php-apigateway.Dockerfile
    tty: true
    ports:
      - "9000:9000"
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    networks:
      - classis-network
    depends_on:
      - postgres-apigateway

  postgres-apigateway:
    container_name: classis-postgres-apigateway
    build: 
      context: ./
      dockerfile: postgres.Dockerfile
    tty: true
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/classis-apigateway:/var/lib/postgresql/data
    networks:
      - classis-network

networks:
  classis-network:
    driver: bridge